---
site_name: oocone
site_description: Unofficial library for interacting with an enocoo energy management system
site_url: https://sleiner.github.io/oocone
repo_url: https://github.com/sleiner/oocone
repo_name: sleiner/oocone
site_dir: site

nav:
    - Home:
          - Overview: index.md
          - Changelog: changelog.md
    - Development:
          - Contributing: contributing.md
          - Code of Conduct: code_of_conduct.md

theme:
    name: material
    palette:
        primary: deep purple
        accent: teal
    font:
        text: Open Sans
        code: Fira Code

markdown_extensions:
    - admonition
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.snippets:
          restrict_base_path: false
          check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist
    - toc:
          permalink: '#'

plugins:
    - search
