---
name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release-pypi:
        name: release-pypi
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up PDM
              uses: pdm-project/setup-pdm@main
              with:
                  cache: true
            - name: Build artifacts
              run: |
                  pip install build
                  python -m build
            - name: Test Build
              run: |
                  python3 -m venv fresh_env
                  . fresh_env/bin/activate
                  pip install dist/*.whl
            - name: Upload to PyPI
              run: pdm publish --no-build
